import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/_Components/Header";
import Footer from "@/_Components/Footer";

const poppins = Poppins({subsets: ["latin"], weight:["300","400","500","600","700"]});

export const metadata: Metadata = {
  title: "Bridge-Mali",
  description: "Generated by create next app",
  icons: "/Logo2.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
